name: Build RustDesk 被控端客户端（Windows）

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 安装 Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-msvc
          override: true

      - name: 安装构建依赖
        run: |
          rustup component add rustfmt
          rustup component add clippy
          cargo install --locked cargo-make

      - name: 设置私钥
        run: |
          mkdir -p pubspecs
          echo "${{ secrets.PRIVKEY }}" > pubspecs/key

      - name: 构建客户端
        run: cargo make --profile production --env-only --no-workspace --makefile ./tasks/Makefile.toml build-client

      - name: 打包客户端（免安装）
        run: |
          mkdir dist
          cp ./target/x86_64-pc-windows-msvc/release/rustdesk.exe ./dist/rustdesk-controlled-client.exe

      - name: 上传构建产物
        uses: actions/upload-artifact@v3
        with:
          name: 被控端客户端
          path: dist/rustdesk-controlled-client.exe
